// Generated by IB v0.3.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation ParserError

@end


@implementation NSNotificationCenter

@end


@implementation NSURLRequest

@end


@implementation Camera

@end


@implementation UIView

@end


@implementation UIAlertView

@end


@implementation ClickedButton

@end


@implementation UIViewController

@end


@implementation InvalidURLError

@end


@implementation InvalidFileError

@end


@implementation BubbleWrap

@end


@implementation BubbleWrap

@end


@implementation NSFNanoStore

@end


@implementation NanoStoreError

@end


@implementation Model

@end


@implementation AnimationChain

@end


@implementation UIView

@end


@implementation Fixnum

@end


@implementation NSArray

@end


@implementation NSString

@end


@implementation Symbol

@end


@implementation UIColor

@end


@implementation UIImage

@end


@implementation Symbol

@end


@implementation SugarCubeNotFoundException

@end


@implementation NSError

@end


@implementation NSIndexPath

@end


@implementation NSLayoutConstraint

@end


@implementation NSNotification

@end


@implementation NSSet

@end


@implementation NSURL

@end


@implementation UIColor

@end


@implementation UIEvent

@end


@implementation UILabel

@end


@implementation UITextField

@end


@implementation UITouch

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation CLLocationCoordinate2D

@end


@implementation UIControl

@end


@implementation UITextView

@end


@implementation UIActionSheet

@end


@implementation UIActivityIndicatorView

@end


@implementation UIAlertView

@end


@implementation UIBarButtonItem

@end


@implementation UIButton

@end


@implementation UISegmentedControl

@end


@implementation NSString

@end


@implementation NSArray

@end


@implementation NSIndexPath

@end


@implementation NSIndexSet

@end


@implementation NSString

@end


@implementation NSURL

@end


@implementation CIColor

@end


@implementation CIFilter

@end


@implementation CIImage

@end


@implementation UIColor

@end


@implementation UIImage

@end


@implementation IndexPath

@end


@implementation NSError

@end


@implementation NSCoder

@end


@implementation NSData

@end


@implementation NSString

@end


@implementation NSURL

@end


@implementation Numeric

@end


@implementation String

@end


@implementation Fixnum

@end


@implementation NSDate

@end


@implementation NSString

@end


@implementation NSUserDefaults

@end


@implementation Object

@end


@implementation NilClass

@end


@implementation NSArray

@end


@implementation NSDictionary

@end


@implementation Fixnum

@end


@implementation NSString

@end


@implementation Numeric

@end


@implementation NSArray

@end


@implementation NSAttributedString

@end


@implementation NSString

@end


@implementation Symbol

@end


@implementation UIImage

@end


@implementation UILabel

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation UINavigationController

@end


@implementation UITabBarController

@end


@implementation UIWebView

@end


@implementation Array

@end


@implementation Date

@end


@implementation Time

@end


@implementation Callback

@end


@implementation CallbackChain

@end


@implementation Array

@end


@implementation Array

@end


@implementation Date

@end


@implementation Date

@end


@implementation Range

@end


@implementation Hash

@end


@implementation Hash

@end


@implementation Hash

@end


@implementation Integer

@end


@implementation Integer

@end


@implementation Object

@end


@implementation Module

@end


@implementation Module

@end


@implementation Module

@end


@implementation NSDictionary

@end


@implementation NSString

@end


@implementation Numeric

@end


@implementation Numeric

@end


@implementation Numeric

@end


@implementation Object

@end


@implementation Object

@end


@implementation Array

@end


@implementation Hash

@end


@implementation Object

@end


@implementation Object

@end


@implementation NilClass

@end


@implementation TrueClass

@end


@implementation FalseClass

@end


@implementation Array

@end


@implementation Hash

@end


@implementation Object

@end


@implementation Array

@end


@implementation String

@end


@implementation String

@end


@implementation String

@end


@implementation String

@end


@implementation Time

@end


@implementation Time

@end


@implementation Duration

@end


@implementation HashWithIndifferentAccess

@end


@implementation Inflections

@end


@implementation NullLogger

@end


@implementation StdoutLogger

@end


@implementation NetworkLogger

@end


@implementation AppDelegate

@end


@implementation BaseViewController

@end


@implementation TimeEntriesController

@end


@implementation UserController

@end


@implementation DataTypeParser

@end


@implementation Network

@end


@implementation NetworkQueue

@end


@implementation Network

@end


@implementation Base

@end


@implementation TimeEntry

@end


@implementation User

@end


@implementation CalendarGridView

@end


@implementation TimeEntryView

@end



