// Generated by IB v0.4.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) setup_sync;
-(IBAction) setup_database;
-(IBAction) setup_window;

@end

@interface BaseViewController: UIViewController
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) view_did_appear;
-(IBAction) preferredStatusBarStyle;

@end

@interface TimeEntriesController: BaseViewController

@property IBOutlet id reusable_hour_view;
@property IBOutlet id reusable_time_entry_view;
@property IBOutlet id date_label_button;
@property IBOutlet id entry_view;

-(IBAction) view_did_appear;
-(IBAction) setup_entry_view;
-(IBAction) setup_selected_date;
-(IBAction) back_pressed;
-(IBAction) forward_pressed;
-(IBAction) update_selected_date:(id) new_date;
-(IBAction) refresh_time_entries;
-(IBAction) menu_button_pressed;
-(IBAction) entry_view_data;

@end

@interface UserController: UIViewController

@property IBOutlet id username_field;
@property IBOutlet id password_field;

@end

@interface Debugger: NSObject
@end

@interface ApiKey: ActiveRecord::Base
-(IBAction) generate_access_token;

@end

@interface Duration: NSObject
-(IBAction) get_range:(id) date;
-(IBAction) value;

@end

@interface Project: SyncModel::Base
@end

@interface TimeEntry: SyncModel::Base
-(IBAction) duration_in_hours;
-(IBAction) date;
-(IBAction) start_time;
-(IBAction) end_time;

@end

@interface User: SyncModel::Base
@end

@interface TimeViewBase: UIView
-(IBAction) reuse:(id) options;

@end

@interface TimeViewContainer: UIScrollView
-(IBAction) hour_height;
-(IBAction) setup_frame;
-(IBAction) refresh;
-(IBAction) data_source;
-(IBAction) new_entry:(id) options;
-(IBAction) new_hour:(id) options;
-(IBAction) reusable_hour_view;

@end

@interface TimeViewEntry: TimeViewBase
@end

@interface TimeViewHour: TimeViewBase
-(IBAction) hour;

@end

