// Generated by IB v0.3.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface ParserError: StandardError







@end


@interface NSNotificationCenter





-(IBAction) observers;
-(IBAction) unobserve:(id) observer;

@end


@interface NSURLRequest





-(IBAction) to_s;

@end


@interface Camera





-(IBAction) initialize:(id) location;
-(IBAction) location;
-(IBAction) imagePickerControllerDidCancel:(id) picker;
-(IBAction) picker;
-(IBAction) dismiss;
-(IBAction) camera_device;
-(IBAction) media_type_to_symbol:(id) media_type;
-(IBAction) symbol_to_media_type:(id) symbol;
-(IBAction) error:(id) type;

@end


@interface UIView





-(IBAction) handle_gesture:(id) recognizer;

@end


@interface UIAlertView





-(IBAction) style;
-(IBAction) cancel_button_index;

@end


@interface ClickedButton





-(IBAction) willPresentAlertView:(id) alert;
-(IBAction) didPresentAlertView:(id) alert;
-(IBAction) alertViewCancel:(id) alert;
-(IBAction) alertViewShouldEnableFirstOtherButton:(id) alert;
-(IBAction) plain_text_field;
-(IBAction) secure_text_field;
-(IBAction) login_text_field;
-(IBAction) password_text_field;

@end


@interface UIViewController





-(IBAction) content_frame;

@end


@interface InvalidURLError: StandardError







@end


@interface InvalidFileError: StandardError







@end


@interface BubbleWrap





-(IBAction) to_s;
-(IBAction) connectionDidFinishLoading:(id) connection;
-(IBAction) show_status_indicator:(id) show;
-(IBAction) create_request;
-(IBAction) set_content_type;
-(IBAction) create_request_body;
-(IBAction) append_payload:(id) body;
-(IBAction) append_form_params:(id) body;
-(IBAction) append_auth_header;
-(IBAction) append_files:(id) body;
-(IBAction) append_body_boundary:(id) body;
-(IBAction) create_url:(id) url_string;
-(IBAction) validate_url:(id) url;
-(IBAction) escape:(id) string;
-(IBAction) convert_payload_to_url;
-(IBAction) log:(id) message;
-(IBAction) escape_line_feeds:(id) hash;
-(IBAction) patch_nsurl_request:(id) request;
-(IBAction) call_delegator_with_response;

@end


@interface BubbleWrap





-(IBAction) initialize:(id) values;
-(IBAction) update:(id) values;
-(IBAction) to_s;
-(IBAction) update_status_description;

@end


@interface NSFNanoStore





-(IBAction) engine;
-(IBAction) save_interval;
-(IBAction) close;
-(IBAction) open;
-(IBAction) delete:(id) objects;
-(IBAction) delete_keys:(id) keys;
-(IBAction) clear;
-(IBAction) save;
-(IBAction) compact;
-(IBAction) clear_index;
-(IBAction) rebuild_index;
-(IBAction) count:(id) clazz;
-(IBAction) transaction;

@end


@interface NanoStoreError: StandardError







@end


@interface Model: NSFNanoObject







@end


@interface AnimationChain





-(IBAction) chains;
-(IBAction) start_chain:(id) chain;
-(IBAction) stop_chain:(id) chain;
-(IBAction) initialize;
-(IBAction) wait:(id) duration;
-(IBAction) do_next;
-(IBAction) start;
-(IBAction) loop:(id) times;
-(IBAction) stop;
-(IBAction) abort;

@end


@interface UIView





-(IBAction) show;
-(IBAction) hide;
-(IBAction) shake:(id) options;
-(IBAction) dummy;

@end


@interface Fixnum





-(IBAction) uicolor:(id) alpha;

@end


@interface NSArray





-(IBAction) uicolor:(id) alpha;

@end


@interface NSString





-(IBAction) uicolor:(id) alpha;

@end


@interface Symbol





-(IBAction) uicolor:(id) alpha;

@end


@interface UIColor





-(IBAction) uicolor:(id) alpha;
-(IBAction) cgcolor;
-(IBAction) invert;
-(IBAction) red;
-(IBAction) green;
-(IBAction) blue;
-(IBAction) alpha;
-(IBAction) to_i;
-(IBAction) to_a;
-(IBAction) hex;
-(IBAction) css_name;
-(IBAction) system_name;

@end


@interface UIImage





-(IBAction) uicolor:(id) alpha;

@end


@interface Symbol





-(IBAction) uidevice;
-(IBAction) uideviceorientation;
-(IBAction) uiinterfaceorientation;
-(IBAction) uiinterfacemask;
-(IBAction) uiautoresizemask;
-(IBAction) uireturnkey;
-(IBAction) uikeyboardtype;
-(IBAction) uitextalignment;
-(IBAction) uilinebreakmode;
-(IBAction) uibaselineadjustment;
-(IBAction) uibordertype;
-(IBAction) nsdatestyle;
-(IBAction) nsnumberstyle;
-(IBAction) uistatusbarstyle;
-(IBAction) uibarmetrics;
-(IBAction) uibarbuttonitem;
-(IBAction) uibarbuttonstyle;
-(IBAction) uibuttontype;
-(IBAction) uicontrolstate;
-(IBAction) uicontrolevent;
-(IBAction) uiactivityindicatorstyle;
-(IBAction) uisegmentedstyle;
-(IBAction) uidatepickermode;
-(IBAction) uicontentmode;
-(IBAction) uianimationcurve;
-(IBAction) uitablestyle;
-(IBAction) uitablerowanimation;
-(IBAction) uitablecellstyle;
-(IBAction) uitablecellaccessorytype;
-(IBAction) uitablecellselectionstyle;
-(IBAction) uitablecellseparatorstyle;
-(IBAction) uialertstyle;
-(IBAction) uiactionstyle;
-(IBAction) uiimagesource;
-(IBAction) uiimagecapture;
-(IBAction) uiimagecamera;
-(IBAction) uiimagequality;
-(IBAction) catimingfunction;
-(IBAction) cglinecap;
-(IBAction) cglinejoin;
-(IBAction) uigesturerecognizerstate;

@end


@interface SugarCubeNotFoundException: Exception







@end


@interface NSError





-(IBAction) to_s;

@end


@interface NSIndexPath





-(IBAction) to_s;

@end


@interface NSLayoutConstraint





-(IBAction) to_s;

@end


@interface NSNotification





-(IBAction) to_s;
-(IBAction) inspect;

@end


@interface NSSet





-(IBAction) to_s;

@end


@interface NSURL





-(IBAction) to_s;
-(IBAction) inspect;

@end


@interface UIColor





-(IBAction) to_s;
-(IBAction) inspect;

@end


@interface UIEvent





-(IBAction) to_s;

@end


@interface UILabel





-(IBAction) to_s:(id) options;

@end


@interface UITextField





-(IBAction) to_s:(id) options;

@end


@interface UITouch





-(IBAction) to_s;

@end


@interface UIView





-(IBAction) to_s:(id) options;

@end


@interface UIViewController





-(IBAction) to_s;

@end


@interface CLLocationCoordinate2D





-(IBAction) distance_to:(id) cl_location_2d;

@end


@interface UIControl





-(IBAction) sugarcube_callbacks;
-(IBAction) call;

@end


@interface UITextView





-(IBAction) sugarcube_callbacks;

@end


@interface UIActionSheet





-(IBAction) dummy;

@end


@interface UIActivityIndicatorView





-(IBAction) large;
-(IBAction) white;
-(IBAction) gray;

@end


@interface UIAlertView





-(IBAction) dummy;

@end


@interface UIBarButtonItem





-(IBAction) sugarcube_handle_action:(id) sender;

@end


@interface UIButton





-(IBAction) custom;
-(IBAction) rounded;
-(IBAction) rounded_rect;
-(IBAction) detail;
-(IBAction) detail_disclosure;
-(IBAction) info;
-(IBAction) info_light;
-(IBAction) info_dark;
-(IBAction) contact;
-(IBAction) contact_add;

@end


@interface UISegmentedControl





-(IBAction) plain:(id) items;
-(IBAction) bordered:(id) items;
-(IBAction) bar:(id) items;
-(IBAction) bezeled:(id) items;

@end


@interface NSString





-(IBAction) document;
-(IBAction) cache;
-(IBAction) app_support;
-(IBAction) resource;
-(IBAction) resource_url;
-(IBAction) info_plist;

@end


@interface NSArray





-(IBAction) nsindexpath;
-(IBAction) nsindexset;
-(IBAction) nsset;

@end


@interface NSIndexPath





-(IBAction) to_a;

@end


@interface NSIndexSet





-(IBAction) to_a;

@end


@interface NSString





-(IBAction) nsurl;
-(IBAction) fileurl;
-(IBAction) escape_url;
-(IBAction) unescape_url;

@end


@interface NSURL





-(IBAction) open;
-(IBAction) nsurlrequest;
-(IBAction) nsmutableurlrequest;

@end


@interface CIColor





-(IBAction) cicolor;

@end


@interface CIFilter





-(IBAction) uiimage;
-(IBAction) ciimage;
-(IBAction) color_invert;
-(IBAction) mask_to_alpha;
-(IBAction) maximum_component;
-(IBAction) minimum_component;
-(IBAction) random_generator;

@end


@interface CIImage





-(IBAction) ciimage;
-(IBAction) apply_filter:(id) filter;

@end


@interface UIColor





-(IBAction) cicolor;

@end


@interface UIImage





-(IBAction) crop:(id) rect;
-(IBAction) in_rect:(id) rect;
-(IBAction) scale_to_fill:(id) new_size;
-(IBAction) scale_within:(id) new_size;
-(IBAction) scale_to:(id) new_size;
-(IBAction) rounded:(id) corner_radius;
-(IBAction) apply_filter:(id) filter;
-(IBAction) cgimage;
-(IBAction) ciimage;
-(IBAction) darken:(id) options;
-(IBAction) rotate:(id) angle_or_direction;
-(IBAction) tileable:(id) insets;
-(IBAction) stretchable:(id) insets;
-(IBAction) alignment_rect:(id) insets;
-(IBAction) masked:(id) mask_image;
-(IBAction) color_at:(id) point;
-(IBAction) at_scale:(id) scale;

@end


@interface IndexPath





-(IBAction) initialize:(id) values;

@end


@interface NSError





-(IBAction) localized;

@end


@interface NSCoder





-(IBAction) bool:(id) key;
-(IBAction) double:(id) key;
-(IBAction) float:(id) key;
-(IBAction) int:(id) key;
-(IBAction) point:(id) key;
-(IBAction) rect:(id) key;
-(IBAction) size:(id) key;

@end


@interface NSData





-(IBAction) nsstring:(id) encoding;
-(IBAction) uiimage:(id) scale;

@end


@interface NSString





-(IBAction) nsdata:(id) encoding;

@end


@interface NSURL





-(IBAction) nsdata;

@end


@interface Numeric





-(IBAction) milliseconds;
-(IBAction) in_milliseconds;
-(IBAction) seconds;
-(IBAction) in_seconds;
-(IBAction) minutes;
-(IBAction) in_minutes;
-(IBAction) hours;
-(IBAction) in_hours;
-(IBAction) days;
-(IBAction) in_days;
-(IBAction) weeks;
-(IBAction) in_weeks;
-(IBAction) months;
-(IBAction) in_months;
-(IBAction) years;
-(IBAction) in_years;

@end


@interface String





-(IBAction) to_date;
-(IBAction) to_timezone;
-(IBAction) to_duration;

@end


@interface Fixnum





-(IBAction) nstimezone;
-(IBAction) before:(id) date;
-(IBAction) ago;
-(IBAction) after:(id) date;
-(IBAction) hence;

@end


@interface NSDate





-(IBAction) string_with_format:(id) format;
-(IBAction) timezone;
-(IBAction) era;
-(IBAction) utc_offset;
-(IBAction) date_array;
-(IBAction) time_array;
-(IBAction) datetime_array;
-(IBAction) start_of_day;
-(IBAction) end_of_day;
-(IBAction) start_of_week:(id) start_day;
-(IBAction) end_of_week:(id) start_day;
-(IBAction) start_of_month;
-(IBAction) end_of_month;
-(IBAction) days_in_month;
-(IBAction) days_in_year;
-(IBAction) days_to_week_start:(id) start_day;
-(IBAction) local_week_start;
-(IBAction) week_day_index:(id) week_day;

@end


@interface NSString





-(IBAction) nstimezone;

@end


@interface NSUserDefaults





-(IBAction) remove:(id) key;

@end


@interface Object





-(IBAction) to_nsuserdefaults;

@end


@interface NilClass





-(IBAction) to_nsuserdefaults;

@end


@interface NSArray





-(IBAction) to_nsuserdefaults;

@end


@interface NSDictionary





-(IBAction) to_nsuserdefaults;

@end


@interface Fixnum





-(IBAction) nth;
-(IBAction) ordinalize;

@end


@interface NSString





-(IBAction) to_number;

@end


@interface Numeric





-(IBAction) percent;
-(IBAction) g;
-(IBAction) in_g;
-(IBAction) radians;
-(IBAction) in_radians;
-(IBAction) degrees;
-(IBAction) in_degrees;
-(IBAction) pi;
-(IBAction) meters;
-(IBAction) in_meters;
-(IBAction) kilometers;
-(IBAction) in_kilometers;
-(IBAction) miles;
-(IBAction) in_miles;
-(IBAction) feet;
-(IBAction) in_feet;
-(IBAction) bytes;
-(IBAction) kilobytes;
-(IBAction) megabytes;
-(IBAction) gigabytes;
-(IBAction) terabytes;
-(IBAction) petabytes;
-(IBAction) exabytes;
-(IBAction) in_bytes;
-(IBAction) in_kilobytes;
-(IBAction) in_megabytes;
-(IBAction) in_gigabytes;
-(IBAction) in_terabytes;
-(IBAction) in_petabytes;
-(IBAction) in_exabytes;
-(IBAction) string_with_style:(id) style;

@end


@interface NSArray





-(IBAction) to_pointer:(id) type;

@end


@interface NSAttributedString





-(IBAction) uilabel;

@end


@interface NSString





-(IBAction) uiimage;
-(IBAction) uifont:(id) size;
-(IBAction) uilabel:(id) font;
-(IBAction) uiimageview;

@end


@interface Symbol





-(IBAction) uifont:(id) size;
-(IBAction) uifontsize;

@end


@interface UIImage





-(IBAction) uiimageview;

@end


@interface UILabel





-(IBAction) fit_to_size:(id) max_size;

@end


@interface UIView





-(IBAction) first_responder;
-(IBAction) unshift:(id) view;
-(IBAction) controller;
-(IBAction) uiimage:(id) use_content_size;
-(IBAction) convert_bounds:(id) destination;
-(IBAction) convert_origin:(id) destination;

@end


@interface UIViewController





-(IBAction) push:(id) view_controller;
-(IBAction) pop;

@end


@interface UINavigationController





-(IBAction) push:(id) view_controller;
-(IBAction) pop:(id) to_view;

@end


@interface UITabBarController





-(IBAction) push:(id) view_controller;

@end


@interface UIWebView





-(IBAction) eval_js:(id) str;

@end


@interface Array





-(IBAction) reverse_each;

@end


@interface Date





-(IBAction) to_s;
-(IBAction) to_date;
-(IBAction) to_time;

@end


@interface Time





-(IBAction) to_date;
-(IBAction) to_time;

@end


@interface Callback





-(IBAction) name;
-(IBAction) next_id;
-(IBAction) apply:(id) code;
-(IBAction) compile;
-(IBAction) append_one:(id) callback;
-(IBAction) prepend_one:(id) callback;
-(IBAction) remove_duplicates:(id) callback;

@end


@interface CallbackChain: Array





-(IBAction) compile;
-(IBAction) append_one:(id) callback;
-(IBAction) prepend_one:(id) callback;
-(IBAction) remove_duplicates:(id) callback;
-(IBAction) reset_callbacks:(id) symbol;

@end


@interface Array





-(IBAction) from:(id) position;
-(IBAction) to:(id) position;
-(IBAction) second;

@end


@interface Array





-(IBAction) to_sentence:(id) options;
-(IBAction) to_formatted_s:(id) format;

@end


@interface Date





-(IBAction) beginning_of_week;
-(IBAction) yesterday;
-(IBAction) tomorrow;
-(IBAction) current;
-(IBAction) ago:(id) seconds;
-(IBAction) since:(id) seconds;
-(IBAction) beginning_of_day;
-(IBAction) end_of_day;
-(IBAction) plus_with_duration:(id) other;
-(IBAction) minus_with_duration:(id) other;
-(IBAction) advance:(id) options;
-(IBAction) change:(id) options;

@end


@interface Date





-(IBAction) to_formatted_s:(id) format;
-(IBAction) readable_inspect;

@end


@interface Range





-(IBAction) sum:(id) identity;

@end


@interface Hash





-(IBAction) with_indifferent_access;

@end


@interface Hash





-(IBAction) transform_keys;
-(IBAction) stringify_keys;
-(IBAction) symbolize_keys;
-(IBAction) deep_stringify_keys;
-(IBAction) deep_symbolize_keys;

@end


@interface Hash





-(IBAction) reverse_merge:(id) other_hash;

@end


@interface Integer





-(IBAction) ordinalize;
-(IBAction) ordinal;

@end


@interface Integer





-(IBAction) months;
-(IBAction) years;

@end


@interface Object





-(IBAction) metaclass;

@end


@interface Module





-(IBAction) attr_internal_ivar_name:(id) attr;

@end


@interface Module





-(IBAction) parent_name;
-(IBAction) parent;
-(IBAction) parents;
-(IBAction) local_constants;

@end


@interface Module





-(IBAction) remove_possible_method:(id) method;

@end


@interface NSDictionary





-(IBAction) to_hash;

@end


@interface NSString





-(IBAction) to_s;

@end


@interface Numeric





-(IBAction) bytes;
-(IBAction) kilobytes;
-(IBAction) megabytes;
-(IBAction) gigabytes;
-(IBAction) terabytes;
-(IBAction) petabytes;
-(IBAction) exabytes;

@end


@interface Numeric





-(IBAction) to_json;

@end


@interface Numeric





-(IBAction) seconds;
-(IBAction) minutes;
-(IBAction) hours;
-(IBAction) days;
-(IBAction) weeks;
-(IBAction) fortnights;
-(IBAction) ago:(id) time;
-(IBAction) since:(id) time;

@end


@interface Object





-(IBAction) presence;

@end


@interface Object





-(IBAction) deep_dup;

@end


@interface Array





-(IBAction) deep_dup;

@end


@interface Hash





-(IBAction) deep_dup;

@end


@interface Object





-(IBAction) instance_values;
-(IBAction) instance_variable_names;

@end


@interface Object





-(IBAction) to_param;

@end


@interface NilClass





-(IBAction) to_param;

@end


@interface TrueClass





-(IBAction) to_param;

@end


@interface FalseClass





-(IBAction) to_param;

@end


@interface Array





-(IBAction) to_param;

@end


@interface Hash





-(IBAction) to_param:(id) namespace;

@end


@interface Object





-(IBAction) to_query:(id) key;

@end


@interface Array





-(IBAction) to_query:(id) key;

@end


@interface String





-(IBAction) at:(id) position;
-(IBAction) from:(id) position;
-(IBAction) to:(id) position;
-(IBAction) first:(id) limit;
-(IBAction) last:(id) limit;

@end


@interface String





-(IBAction) squish;

@end


@interface String





-(IBAction) pluralize:(id) count;
-(IBAction) singularize;
-(IBAction) constantize;
-(IBAction) safe_constantize;
-(IBAction) camelize:(id) first_letter;
-(IBAction) titleize;
-(IBAction) underscore;
-(IBAction) dasherize;
-(IBAction) demodulize;
-(IBAction) deconstantize;
-(IBAction) tableize;
-(IBAction) classify;
-(IBAction) humanize;
-(IBAction) foreign_key:(id) separate_class_name_and_id_with_underscore;

@end


@interface String





-(IBAction) strip_heredoc;

@end


@interface Time





-(IBAction) current;
-(IBAction) seconds_since_midnight;
-(IBAction) seconds_until_end_of_day;
-(IBAction) change:(id) options;
-(IBAction) advance:(id) options;
-(IBAction) ago:(id) seconds;
-(IBAction) since:(id) seconds;
-(IBAction) beginning_of_day;
-(IBAction) end_of_day;
-(IBAction) beginning_of_hour;
-(IBAction) end_of_hour;
-(IBAction) beginning_of_minute;
-(IBAction) end_of_minute;
-(IBAction) all_day;
-(IBAction) all_week:(id) start_day;
-(IBAction) all_month;
-(IBAction) all_quarter;
-(IBAction) all_year;
-(IBAction) plus_with_duration:(id) other;
-(IBAction) minus_with_duration:(id) other;
-(IBAction) compare_with_coercion:(id) other;

@end


@interface Time





-(IBAction) to_formatted_s:(id) format;

@end


@interface Duration: BasicObject





-(IBAction) since:(id) time;
-(IBAction) ago:(id) time;
-(IBAction) inspect;
-(IBAction) as_json:(id) options;

@end


@interface HashWithIndifferentAccess: Hash





-(IBAction) with_indifferent_access;
-(IBAction) nested_under_indifferent_access;
-(IBAction) initialize:(id) constructor;
-(IBAction) default:(id) key;
-(IBAction) update:(id) other_hash;
-(IBAction) dup;
-(IBAction) reverse_merge:(id) other_hash;
-(IBAction) replace:(id) other_hash;
-(IBAction) delete:(id) key;
-(IBAction) to_hash;
-(IBAction) convert_key:(id) key;
-(IBAction) convert_value:(id) value;

@end


@interface Inflections





-(IBAction) initialize;
-(IBAction) initialize_dup:(id) orig;
-(IBAction) acronym:(id) word;
-(IBAction) clear:(id) scope;
-(IBAction) inflections;

@end


@interface NullLogger





-(IBAction) log:(id) string;

@end


@interface StdoutLogger





-(IBAction) log:(id) string;

@end


@interface NetworkLogger





-(IBAction) log:(id) string;

@end


@interface AppDelegate





-(IBAction) setup_sync;
-(IBAction) setup_database;
-(IBAction) setup_window;

@end


@interface BaseViewController: UIViewController







@end


@interface TimeEntriesController: BaseViewController

@property IBOutlet id calendar_view;
@property IBOutlet id date_label_button;



-(IBAction) viewDidAppear:(id) animated;
-(IBAction) back_pressed;
-(IBAction) forward_pressed;
-(IBAction) update_date_label;
-(IBAction) refresh_time_entries;
-(IBAction) render_entries;
-(IBAction) menu_button_pressed;

@end


@interface UserController: UIViewController

@property IBOutlet id username_field;
@property IBOutlet id password_field;



-(IBAction) viewDidAppear:(id) animated;
-(IBAction) login:(id) sender;
-(IBAction) load_persisted_credentials;
-(IBAction) save_persisted_credentials;
-(IBAction) segue_to_time_entries;

@end


@interface DataTypeParser





-(IBAction) initialize:(id) obj;
-(IBAction) parse;

@end


@interface Network





-(IBAction) initialize:(id) params;
-(IBAction) execute;
-(IBAction) to_s;
-(IBAction) add_to_queue:(id) priority;
-(IBAction) auth_action;
-(IBAction) watch_for_csrf_token;

@end


@interface NetworkQueue





-(IBAction) setup_queue;
-(IBAction) queue;
-(IBAction) execute;
-(IBAction) unlock_and_continue;
-(IBAction) verbose_count;
-(IBAction) count;
-(IBAction) next_call;

@end


@interface Network





-(IBAction) initialize:(id) params;
-(IBAction) execute;
-(IBAction) to_s;
-(IBAction) add_to_queue:(id) priority;
-(IBAction) auth_action;
-(IBAction) watch_for_csrf_token;

@end


@interface Base: NanoStore





-(IBAction) to_hash;
-(IBAction) payload;

@end


@interface TimeEntry: SyncModel





-(IBAction) duration_in_hours;
-(IBAction) date;
-(IBAction) start_time;
-(IBAction) end_time;

@end


@interface User: SyncModel







@end


@interface CalendarGridView: UIView





-(IBAction) initWithCoder:(id) coder;
-(IBAction) setup_size;
-(IBAction) drawRect:(id) rect;
-(IBAction) set_children:(id) time_entries;
-(IBAction) hour_height:(id) n;
-(IBAction) top_for_date:(id) date;
-(IBAction) grid;
-(IBAction) top_for_hour:(id) hour;
-(IBAction) time_labels;
-(IBAction) half_hour_height;
-(IBAction) grid_left;
-(IBAction) remove_children;

@end


@interface TimeEntryView: UIView





-(IBAction) initWithFrame:(id) frame;
-(IBAction) drawRect:(id) rect;
-(IBAction) project_name;
-(IBAction) update_label;
-(IBAction) back_color;
-(IBAction) border_color;
-(IBAction) text_color;
-(IBAction) text_shadow;

@end



