// Generated by IB v0.4.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation BaseViewController
@end

@implementation TimeEntriesController
@end

@implementation UserController
@end

@implementation Debugger
@end

@implementation ApiKey
@end

@implementation Duration
@end

@implementation Project
@end

@implementation TimeEntry
@end

@implementation User
@end

@implementation TimeViewBase
@end

@implementation TimeViewContainer
@end

@implementation TimeViewEntry
@end

@implementation TimeViewHour
@end

