// Generated by IB v0.2.10 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation Camera

@end


@implementation ParserError

@end


@implementation NSNotificationCenter

@end


@implementation NSURLRequest

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation Response

@end


@implementation Query

@end


@implementation InvalidURLError

@end


@implementation Hash

@end


@implementation Object

@end


@implementation Array

@end


@implementation Hash

@end


@implementation String

@end


@implementation Inflections

@end


@implementation ValidationSpecificationError

@end


@implementation RecordInvalid

@end


@implementation Store

@end


@implementation Model

@end


@implementation PersistFileError

@end


@implementation RelationIsNilError

@end


@implementation AdapterNotFoundError

@end


@implementation RecordNotSaved

@end


@implementation Column

@end


@implementation ArrayFinderQuery

@end


@implementation ModelNotSetError

@end


@implementation FieldBindingMap

@end


@implementation Debug

@end


@implementation Module

@end


@implementation SQLite3Adapter

@end


@implementation SQLScope

@end


@implementation SQLContext

@end


@implementation SQLDBAdapter

@end


@implementation SQLCondition

@end


@implementation AbstractRelation

@end


@implementation CollectionRelation

@end


@implementation RelationArray

@end


@implementation InstanceRelation

@end


@implementation Join

@end


@implementation FMDBAdapter

@end


@implementation Transaction

@end


@implementation BaseDBAdapter

@end


@implementation PersistFileError

@end


@implementation VersionNumberError

@end


@implementation AnimationChain

@end


@implementation CLLocationCoordinate2D

@end


@implementation String

@end


@implementation SugarNotFoundException

@end


@implementation Fixnum

@end


@implementation NSArray

@end


@implementation NSCoder

@end


@implementation NSData

@end


@implementation NSDate

@end


@implementation NSIndexPath

@end


@implementation IndexPath

@end


@implementation NSIndexSet

@end


@implementation NSString

@end


@implementation NSString

@end


@implementation NSURL

@end


@implementation NSUserDefaults

@end


@implementation Object

@end


@implementation NilClass

@end


@implementation NSArray

@end


@implementation NSDictionary

@end


@implementation Numeric

@end


@implementation Symbol

@end


@implementation Symbol

@end


@implementation Numeric

@end


@implementation NSError

@end


@implementation NSLayoutConstraint

@end


@implementation NSNotification

@end


@implementation NSSet

@end


@implementation NSURL

@end


@implementation UIColor

@end


@implementation UIEvent

@end


@implementation UILabel

@end


@implementation UITextField

@end


@implementation UITouch

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation UIActionSheet

@end


@implementation UIActivityIndicatorView

@end


@implementation UIAlertView

@end


@implementation UIBarButtonItem

@end


@implementation UIButton

@end


@implementation UIColor

@end


@implementation UIControl

@end


@implementation UIImage

@end


@implementation UILabel

@end


@implementation UISegmentedControl

@end


@implementation UITextView

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation UINavigationController

@end


@implementation UITabBarController

@end


@implementation AppDelegate

@end


@implementation BaseViewController

@end


@implementation LeftMenuController

@end


@implementation TimeEntriesController

@end


@implementation UserController

@end


@implementation Base

@end


@implementation NetworkQueue

@end


@implementation Network

@end


@implementation TimeEntry

@end


@implementation User

@end


@implementation CalendarGridView

@end


@implementation TimeEntryView

@end


@implementation String

@end



